version: 2.1

executors:
  nodejs:
    docker:
      - image: cimg/node:16.15.0
jobs:
  publish:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fa:cc:6f:c9:f0:53:2f:7a:eb:05:22:fd:9d:b5:83:c0"
      - run:
          name: Setup GIT email
          command: git config --global user.email "developer@keen.io"
      - run:
          name: Setup GIT user
          command: git config --global user.name "Keen Developer"
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Install dependencies
          command: yarn && npx lerna bootstrap
      - run:
          name: Build packages
          command: npx lerna run build --concurrency 2
      - run:
          name: Assume packages.json in packages unchanged
          command: git update-index --assume-unchanged packages/*/package.json
      - run:
          name: Bump version of changed packages
          command: npx lerna version --conventional-commits --no-push --yes
      - run:
          name: Publish
          command: npx lerna publish from-git --yes --no-verify-access
      - run:
          name: Push changes
          command: git push --follow-tags --no-verify origin main
  test:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit Tests
          command: yarn test:ci
  build:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npx lerna run build --concurrency 2

workflows:
  version: 2
  release:
    jobs:
      - publish:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
  ci:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              ignore: /.*/
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              ignore: /.*/
